message_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('message', views.message_view, name='message_view'),

]

message_servise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from message_servise import settings

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('message_app.urls')),

)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

message_app/models.py
from django.db import models
from django.utils.translation import gettext as _

from message_app.validators import phone_validator


class Message(models.Model):
    class ErrorType(models.TextChoices):
        DESCRIPTION_ERROR = 'DE', _('Description error')
        COMBAT_DATA_ERROR = 'CDE', _('Combat data error')
        NAME_ERROR = 'NE', _('Name error')
        IMG_ERROR = 'IE', _('Image error')
        FRONT_DISPLAY_ERROR = 'FDE', _('Front display error')
        OTHER_ERROR = 'OE', _('Other error')

    name = models.CharField(_('Name'), max_length=200)
    phone = models.CharField(_('Phone'), max_length=20, validators=[phone_validator])
    email = models.EmailField(_('Email'))
    type_error = models.CharField(_('Type'), max_length=200, choices=ErrorType.choices, default=ErrorType.OTHER_ERROR)
    text_error = models.CharField(_('Text'), max_length=202)

    def __str__(self):
        return f'message from {self.name}'

message_app/forms.py
from django import forms
from django.utils.translation import gettext as _

from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = (
            'name',
            'phone',
            'email',
            'type_error',
            'text_error'
        )
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': _('Max')}),
            'phone': forms.TextInput(attrs={'placeholder': '+7(858)855-95-95'}),
            'email': forms.TextInput(attrs={'placeholder': 'hgh@gmail.com'}),
            'text_error': forms.Textarea(attrs={'placeholder': _('All error text')}),
        }

    # def save(self, commit=True):
    # pass

message_app/views.py
from django.contrib import messages
from django.shortcuts import render
from django.utils.translation import gettext as _

from .forms import MessageForm


def message_view(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            intance = form.save()
            messages.success(request, _('Message is succesfully sent'))
        else:
            messages.error(request, _('Invalid form'), extra_tags='danger')

    else:
        form = MessageForm()

    return render(
        request=request,
        template_name='message_app/message_form.html',
        context={
            'form': form,
        },

    )

message_app/templates/message_app/email_message.html
<!DOCTYPE html>

<html lang="en">
<head>
    {% load crispy_forms_tags %}
    <meta charset="UTF-8">
    <title>Email message</title>
</head>
<body>
<h1>Error message resived </h1>
<div>Error type:  {{ message.get_type_error_display }}</div>
<div>Error name:  {{ message.name}}</div>
<div>Error text:  {{ message.type_text}}</div>
<div>Error phone:  {{ message.phone}}</div>
<div>Error email:  {{ message.email}}</div>

</body>
</html>

message_app/templates/message_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load crispy_forms_tags %}
    <meta charset="UTF-8">
    <title>Message to admin</title>
</head>
<body>
{% include 'message_app/languege_switch.html' %}
{% block content  %}

{% endblock %}
</body>
</html>

message_app/templates/message_app/languege_switch.html
{% load crispy_forms_tags %}
{% load i18n %}


<div id = 'header'>
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    <div class="language">
        <p>{% translate 'Language' %}:</p>
        <ul class="language">
            {% for language in languages %}
                <li>
                    <a href="/{{language.code}}"{% if language.code == LANGUAGE_CODE     %} class="selected"{% endif %}>
                        {{language.name_local}} ({{language.code}})
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

message_app/templates/message_app/message_form.html
{% extends 'message_app/index.html'%}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
<h1>{{LANGUAGE_CODE}}</h1>
<div class='container'>
    <h1>{% translate 'Describe problem' %}</h1>
    <div class="messages">
        {% for message in messages %}
        <div {%if message.tags  %} class="alert alert-{{message.tags}}" {% endif %}>
            {{message}}
        </div>
        {% endfor %}
    </div>
    </br>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success"> {% translate 'Send message' %}</button>
    </form>

</div>
{% endblock %}

message_app/templates/message_app/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load crispy_forms_tags %}
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>
<h1>Message send successfully</h1>
<h3>To return - touch button</h3>
<button ><a href="{% message_servise/message_app/index.html %}">Return</a> </button>
</body>
</html>